version: "3.9"
services:
  postgres:
    container_name: postgres_container_2
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "localPsql"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5500:5432"